BEGIN;
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "connectionType" TEXT NOT NULL DEFAULT 'HTTP';
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "readerIp" TEXT;
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "sourcePort" INTEGER;
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "tcpConnected" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "connectionId" TEXT;
ALTER TABLE rfid_readers ADD COLUMN IF NOT EXISTS "lastGatewaySeenAt" TIMESTAMP(3);
COMMIT;
